"""Create sensor_data table

Revision ID: e128e25891d1
Revises:
Create Date: 2025-07-20 17:48:55.220081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e128e25891d1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensor_data",
        sa.Column("device_id", sa.Text(), nullable=False),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("timestamp"),
    )

    op.execute(
        """
        SELECT create_hypertable('sensor_data', 'timestamp', if_not_exists => TRUE);
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sensor_data")
    # ### end Alembic commands ###
